# This is a basic workflow to help you get started with Actions

name: "1 - [FEAT] Build & PR"

# Controls when the workflow will run
on:
  push:
    branches:
     - 'feature**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DoBuildThing:
    uses: UKNorthernlad/actions/.github/workflows/blank.yml@v1.0.0
    secrets: inherit

  DoAppThing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  CreatePR:
    runs-on: ubuntu-latest
    needs:
      - DoAppThing
      - DoBuildThing
    steps: 
          - name: Create Pull Request
            uses: peter-evans/create-pull-request@v5
            with:
              commit-message: "Automated changes"
              title: "Automated Pull Request"
              body: "This pull request was automatically created by a GitHub Action."
  
